# Generated by Django 2.1.1 on 2018-09-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('B1', 'B.Tech. 1st Year'), ('B2', 'B.Tech. 2nd Year'), ('B3', 'B.Tech. 3rd Year'), ('B4', 'B.Tech. 4th Year'), ('M1', 'M.Tech. 1st Year'), ('M2', 'M.Tech. 2nd Year')], max_length=2)),
                ('year', models.CharField(choices=[('B1', 'B.Tech. 1st Year'), ('B2', 'B.Tech. 2nd Year'), ('B3', 'B.Tech. 3rd Year'), ('B4', 'B.Tech. 4th Year'), ('M1', 'M.Tech. 1st Year'), ('M2', 'M.Tech. 2nd Year')], max_length=2)),
            ],
        ),
    ]
