# Generated by Django 2.1.1 on 2018-09-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science and Engineering'), ('MA', 'Mathematics'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering')], max_length=2),
        ),
    ]
