# Generated by Django 2.1.1 on 2018-09-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180923_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_conversation_user1', to='website.Users')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_conversation_user2', to='website.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, editable=False)),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('N', 'None'), ('F', 'Freeze'), ('P', 'Pending'), ('V', 'Verified'), ('R', 'Rejected')], default='P', editable=False, max_length=1)),
                ('point_comment', models.TextField()),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='point',
            name='point_comment',
        ),
        migrations.RemoveField(
            model_name='point',
            name='user_verify',
        ),
        migrations.AddField(
            model_name='request',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Point'),
        ),
        migrations.AddField(
            model_name='request',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Section'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_receiver', to='website.Users'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_sender', to='website.Users'),
        ),
        migrations.AddField(
            model_name='notification',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Point'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_receiver', to='website.Users'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_sender', to='website.Users'),
        ),
    ]
