# Generated by Django 2.1.1 on 2018-09-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180923_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='point',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='timestamp',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='timestamp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='point_comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateField(null=True),
        ),
    ]
