# Generated by Django 2.1.2 on 2018-10-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180923_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
