# Generated by Django 2.1.2 on 2018-10-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_users_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
