# Generated by Django 2.1.2 on 2018-10-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20181014_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='resume_id',
            new_name='resume',
        ),
    ]
