# Generated by Django 2.1.2 on 2018-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20181014_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='position_in_list',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='point_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='request',
            name='point_comment',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_status',
        ),
        migrations.RemoveField(
            model_name='request',
            name='section_id',
        ),
        migrations.AddField(
            model_name='point',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='point',
            name='status',
            field=models.CharField(choices=[('N', 'None'), ('F', 'Freeze'), ('P', 'Pending'), ('V', 'Verified'), ('R', 'Rejected')], default='P', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='point',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='privilege',
            field=models.BooleanField(default=False),
        ),
    ]
