# Generated by Django 2.1.2 on 2018-11-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20181021_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user_receiver',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='user_sender',
            new_name='sender',
        ),
    ]
