# Generated by Django 2.1.2 on 2018-11-02 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20181102_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user_receiver',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user_sender',
            new_name='sender',
        ),
    ]
