# Generated by Django 2.1.3 on 2018-11-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_notification_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='n_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
