# Generated by Django 2.1.3 on 2018-11-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_conversation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
