# Generated by Django 2.1.1 on 2018-11-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('BU', 'Bullet'), ('BL', 'Block'), ('M', 'Multi')], default='BU', max_length=2),
        ),
    ]
