# Generated by Django 2.1.3 on 2018-11-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.CharField(default='profiles/default/default.png', max_length=100),
        ),
    ]
