# Generated by Django 2.1.1 on 2018-11-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20181126_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('BU', 'Bullet'), ('BL', 'Block'), ('M2', '2 Columns'), ('M3', '3 Columns'), ('M4', '4 Columns')], default='BU', editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('BU', 'Bullet'), ('BL', 'Block'), ('M2', '2 Columns'), ('M3', '3 Columns'), ('M4', '4 Columns')], default='BU', max_length=2),
        ),
    ]
