# Generated by Django 2.1.3 on 2018-11-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20181126_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='position',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
