# Generated by Django 2.1.1 on 2018-11-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_conversation_timestamp'),
        ('website', '0025_auto_20181126_1609'),
    ]

    operations = [
    ]
