# Generated by Django 2.1.3 on 2018-11-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20181126_2017'),
        ('website', '0026_merge_20181126_1736'),
    ]

    operations = [
    ]
