# Generated by Django 2.1.3 on 2018-11-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_merge_20181126_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
